### PR TITLE
Server descriptions

### LINKED ISSUE #61: Html trainer info are not showing
Trainer infos which contain html are loaded through an iframe (check index.js, updatePlayerInfo). It then calls "trainerinfo.html" with get parameters that dictates the content : https://github.com/po-devs/webclient/blob/gh-pages/trainerinfo.html

There seems to be an error there. You can use this example to reproduce the problem: (page shouldn't be blank)
http://po-devs.github.io/webclient/trainerinfo.html?content=PGRpdiBjbGFzcz0iaWZyYW1lLXRyYWluZXItaW5mbyI+PGNlbnRlcj5EYXkgYmVmb3JlIHllc3RlcmRheSBJIHNhdyBhIHJhYmJpdDxicj5ZZXN0ZXJkYXkgSSBzYXcgYSBkZWVyPGJyPkFuZCB0b2RheSwgeW91PGJyPjxpbWcgc3JjPSJodHRwOi8vcG9rZW1vbi1vbmxpbmUuZXUvaW1hZ2VzL3Bva2Vtb24vYmxhY2std2hpdGUvNDc4LnBuZyI+PC9jZW50ZXI+PC9kaXY+&css=ZmlsZTovLy9DOi9Vc2Vycy9Db21wYXEvY29kZS93ZWJjbGllbnQvY3NzL3dlYmNsaWVudC5jc3M=

### LINKED ISSUE #74: Show server descriptions in registry
Use an iframe system similar to the trainer infos.

### LINKED ISSUE #79: Commands being sent before connected
Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': already in CONNECTING state.

Just check if the socket exists in connect()

### PR DESCRIPTION
**Pull request by HRDepartment**
Fix #61 
Fix #74
Fix #79

i8pf

I replaced inheritance with inherits. It has the same function, but it's a lot faster (and smaller and whatnot).

type="text/javascript" just slows everything down, so that's gone too.

In channels.js, using a jquery animation fixed a problem for me (in Chrome only?) where it wouldn't automatically scroll down.

And finally, that old exit warning is commented out (it has no purpose right now).

### CODE REVIEW

File: js/style.js [hunk 1]
```diff
@@ -33,11 +33,7 @@ $(document).ready(function() {
 	});
     $("#battle-html").load("battle.html");
 	$("#teambuilder").load("teambuilder.html", function() {
-		
 		/* Teambuilder */
-
-        $(document).ready(function() {
-		    var tb = new teambuilder();
-        });
+        var tb = new teambuilder();
```
Comment (coyotte508) [inline js/style.js]: Are you really, really sure about that?

When teambuilder.html is loaded, and it's not on localhost but on a distant websites, if not cached the associated js files take some time to be loaded after that, and that's why there's a second document.ready(). Because there was a bug.

File: teambuilder.html [hunk 2]
```diff
@@ -1,129 +1,129 @@
...
+<script src="js/db/status/status.js"></script>
+
+<script src="js/db/types/types.js"></script>
+
+<script src="js/db/abilities/abilities.js"></script>
+<script src="js/db/abilities/ability_messages.js"></script>
+
+<script src="js/pokeinfo.js"></script>
+
+<script src="js/teambuilder.js"></script>
```
Comment (coyotte508) [inline teambuilder.html:126]: why is it faster? =o

Comment (HRDepartment) [inline teambuilder.html:126]: Additional parsing time and it takes longer to load from cache/web server. Minuscule, but it's still there (especially when requesting from the server).

The server decides the MIME, not the client.

JavaScript is the default anyway, so it doesn't matter if it's there or not (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)

File: js/style.js (hunk 1 above)
Comment (HRDepartment) [inline js/style.js]: .ready is for DOMContentLoaded, which is only called once. If the dom has already been loaded jQuery just calls the function right away (well, defers it with setTimeout). Maybe jQuery.load is more appropriate?
